### ISSUE TITLE
extension breaks

### ISSUE THREAD

**Issue by luceos** [justoverclockl/auto-post-count-badge#1]
We encountered an issue on a production website using your extension:

https://github.com/justoverclockl/auto-post-count-badge/blob/516391eb54cb360e90241e1eda6e5d988bbad447/js/src/forum/index.js#L13

![image](https://user-images.githubusercontent.com/504687/144818934-53794f25-49f9-4958-a085-bf4521b1c9ea.png)

You should probably not use `data.attributes` but the `commentCount`: `post.user().commentCount()` if you want it to null if the property is unavailable use: `post.user()?.commentCount()`.

**Comment by justoverclockl** [comment]
fixed
